"""init

Revision ID: 6f5e2b00b51a
Revises: 
Create Date: 2026-03-25 21:05:27.472786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5e2b00b51a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), server_default=sa.text("'ollama'"), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('llm_api_key', sa.String(length=500), nullable=True),
    sa.Column('threshold_apply_now', sa.SmallInteger(), server_default=sa.text('80'), nullable=False),
    sa.Column('threshold_good_match', sa.SmallInteger(), server_default=sa.text('60'), nullable=False),
    sa.Column('threshold_study_first', sa.SmallInteger(), server_default=sa.text('40'), nullable=False),
    sa.Column('weight_skills', sa.SmallInteger(), server_default=sa.text('35'), nullable=False),
    sa.Column('weight_experience', sa.SmallInteger(), server_default=sa.text('25'), nullable=False),
    sa.Column('weight_education', sa.SmallInteger(), server_default=sa.text('15'), nullable=False),
    sa.Column('weight_languages', sa.SmallInteger(), server_default=sa.text('10'), nullable=False),
    sa.Column('weight_preferences', sa.SmallInteger(), server_default=sa.text('15'), nullable=False),
    sa.Column('cv_template_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'nueva'"), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'title', name='ux_job_company_title'),
    sa.UniqueConstraint('source_url', name='ux_job_source_url')
    )
    op.create_index('ix_job_platform', 'job', ['platform'], unique=False)
    op.create_index('ix_job_status', 'job', ['status'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'México'"), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('other_links', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('modality', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('platforms', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('schedule_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('obtained_date', sa.Date(), nullable=True),
    sa.Column('verification_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), server_default=sa.text("'MXN'"), nullable=False),
    sa.Column('modalities', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('preferred_locations', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('contract_types', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', name='uq_job_preference_profile_id')
    )
    op.create_table('kit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('cv_html', sa.String(), nullable=False),
    sa.Column('cv_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('email_subject', sa.String(length=300), nullable=True),
    sa.Column('email_body', sa.String(), nullable=True),
    sa.Column('short_message', sa.String(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('study_guide', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kit_job_version', 'kit', ['job_id', 'version'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score_overall', sa.SmallInteger(), nullable=False),
    sa.Column('score_skills', sa.SmallInteger(), nullable=False),
    sa.Column('score_experience', sa.SmallInteger(), nullable=False),
    sa.Column('score_education', sa.SmallInteger(), nullable=False),
    sa.Column('score_languages', sa.SmallInteger(), nullable=False),
    sa.Column('score_preferences', sa.SmallInteger(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('matching_skills', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('gap_skills', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('differentiators', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_match_result_job_id')
    )
    op.create_index('ix_match_classification', 'match_result', ['classification'], unique=False)
    op.create_index('ix_match_score_overall', 'match_result', ['score_overall'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'job_id', name='uq_search_job')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('years_experience', sa.SmallInteger(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('technologies', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience')
    op.drop_table('skill')
    op.drop_table('search_job')
    op.drop_table('notification')
    op.drop_index('ix_match_score_overall', table_name='match_result')
    op.drop_index('ix_match_classification', table_name='match_result')
    op.drop_table('match_result')
    op.drop_table('language')
    op.drop_index('ix_kit_job_version', table_name='kit')
    op.drop_table('kit')
    op.drop_table('job_preference')
    op.drop_table('education')
    op.drop_table('course')
    op.drop_table('certification')
    op.drop_table('search')
    op.drop_table('profile')
    op.drop_index('ix_job_status', table_name='job')
    op.drop_index('ix_job_platform', table_name='job')
    op.drop_table('job')
    op.drop_table('config')
    # ### end Alembic commands ###
